alter table CAR_MODEL drop constraint UC_CAR_PROJECT_MODELL_NAME;
alter table CAR_MODEL add constraint UC_CAR_PROJECT_MODELL_NAME UNIQUE (CAR_PROJECT_ID, MODEL_NAME) INITIALLY DEFERRED  DEFERRABLE;
