create index IDX_CAR_MODEL_BRAND on CAR_MODEL(CAR_BRAND);
create index IDX_CAR_PROPERTY_FAMILY on CAR_MODEL_PROPERTY(PROPERTY_FAMILY);

SELECT * FROM CAR_MODEL m
LEFT JOIN CAR_MODEL_PROPERTY p ON m.ID = p.CAR_MODEL_ID
WHERE m.CAR_BRAND = 'AUDI' AND p.CAR_MODEL_ID = m.ID AND p.PROPERTY_FAMILY = 'Family 2';
